// Code generated by gowsdl DO NOT EDIT.

package xmlda

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type QName string

type ServerState string

const (
	ServerStateRunning ServerState = "running"

	ServerStateFailed ServerState = "failed"

	ServerStateNoConfig ServerState = "noConfig"

	ServerStateSuspended ServerState = "suspended"

	ServerStateTest ServerState = "test"

	ServerStateCommFault ServerState = "commFault"
)

type InterfaceVersion string

const (
	InterfaceVersionXML_DA_Version_1_0 InterfaceVersion = "XML_DA_Version_1_0"

	InterfaceVersionDX_Version_1_0 InterfaceVersion = "DX_Version_1_0"
)

type QualityBits string

const (
	QualityBitsBad QualityBits = "bad"

	QualityBitsBadConfigurationError QualityBits = "badConfigurationError"

	QualityBitsBadNotConnected QualityBits = "badNotConnected"

	QualityBitsBadDeviceFailure QualityBits = "badDeviceFailure"

	QualityBitsBadSensorFailure QualityBits = "badSensorFailure"

	QualityBitsBadLastKnownValue QualityBits = "badLastKnownValue"

	QualityBitsBadCommFailure QualityBits = "badCommFailure"

	QualityBitsBadOutOfService QualityBits = "badOutOfService"

	QualityBitsBadWaitingForInitialData QualityBits = "badWaitingForInitialData"

	QualityBitsUncertain QualityBits = "uncertain"

	QualityBitsUncertainLastUsableValue QualityBits = "uncertainLastUsableValue"

	QualityBitsUncertainSensorNotAccurate QualityBits = "uncertainSensorNotAccurate"

	QualityBitsUncertainEUExceeded QualityBits = "uncertainEUExceeded"

	QualityBitsUncertainSubNormal QualityBits = "uncertainSubNormal"

	QualityBitsGood QualityBits = "good"

	QualityBitsGoodLocalOverride QualityBits = "goodLocalOverride"
)

type LimitBits string

const (
	LimitBitsNone LimitBits = "none"

	LimitBitsLow LimitBits = "low"

	LimitBitsHigh LimitBits = "high"

	LimitBitsConstant LimitBits = "constant"
)

type BrowseFilter string

const (
	BrowseFilterAll BrowseFilter = "all"

	BrowseFilterBranch BrowseFilter = "branch"

	BrowseFilterItem BrowseFilter = "item"
)

type GetStatus struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ GetStatus"`

	LocaleID string `xml:"LocaleID,omitempty" json:"LocaleID,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`
}

type GetStatusResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ GetStatusResponse"`

	GetStatusResult *ReplyBase `xml:"GetStatusResult,omitempty" json:"GetStatusResult,omitempty"`

	Status *ServerStatus `xml:"Status,omitempty" json:"Status,omitempty"`
}

type GetProperties struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ GetProperties"`

	ItemIDs []*ItemIdentifier `xml:"ItemIDs,omitempty" json:"ItemIDs,omitempty"`

	PropertyNames []*QName `xml:"PropertyNames,omitempty" json:"PropertyNames,omitempty"`

	LocaleID string `xml:"LocaleID,attr,omitempty" json:"LocaleID,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ReturnAllProperties bool `xml:"ReturnAllProperties,attr,omitempty" json:"ReturnAllProperties,omitempty"`

	ReturnPropertyValues bool `xml:"ReturnPropertyValues,attr,omitempty" json:"ReturnPropertyValues,omitempty"`

	ReturnErrorText bool `xml:"ReturnErrorText,attr,omitempty" json:"ReturnErrorText,omitempty"`
}

type GetPropertiesResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ GetPropertiesResponse"`

	GetPropertiesResult *ReplyBase `xml:"GetPropertiesResult,omitempty" json:"GetPropertiesResult,omitempty"`

	PropertyLists []*PropertyReplyList `xml:"PropertyLists,omitempty" json:"PropertyLists,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`
}

type Subscribe struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ Subscribe"`

	Options *RequestOptions `xml:"Options,omitempty" json:"Options,omitempty"`

	ItemList *SubscribeRequestItemList `xml:"ItemList,omitempty" json:"ItemList,omitempty"`

	ReturnValuesOnReply bool `xml:"ReturnValuesOnReply,attr,omitempty" json:"ReturnValuesOnReply,omitempty"`

	SubscriptionPingRate int32 `xml:"SubscriptionPingRate,attr,omitempty" json:"SubscriptionPingRate,omitempty"`
}

type SubscribeResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ SubscribeResponse"`

	SubscribeResult *ReplyBase `xml:"SubscribeResult,omitempty" json:"SubscribeResult,omitempty"`

	RItemList *SubscribeReplyItemList `xml:"RItemList,omitempty" json:"RItemList,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`

	ServerSubHandle string `xml:"ServerSubHandle,attr,omitempty" json:"ServerSubHandle,omitempty"`
}

type SubscriptionPolledRefresh struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ SubscriptionPolledRefresh"`

	Options *RequestOptions `xml:"Options,omitempty" json:"Options,omitempty"`

	ServerSubHandles []string `xml:"ServerSubHandles,omitempty" json:"ServerSubHandles,omitempty"`

	HoldTime XSDDateTime `xml:"HoldTime,attr,omitempty" json:"HoldTime,omitempty"`

	WaitTime int32 `xml:"WaitTime,attr,omitempty" json:"WaitTime,omitempty"`

	ReturnAllItems bool `xml:"ReturnAllItems,attr,omitempty" json:"ReturnAllItems,omitempty"`
}

type SubscriptionPolledRefreshResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ SubscriptionPolledRefreshResponse"`

	SubscriptionPolledRefreshResult *ReplyBase `xml:"SubscriptionPolledRefreshResult,omitempty" json:"SubscriptionPolledRefreshResult,omitempty"`

	InvalidServerSubHandles []string `xml:"InvalidServerSubHandles,omitempty" json:"InvalidServerSubHandles,omitempty"`

	RItemList []*SubscribePolledRefreshReplyItemList `xml:"RItemList,omitempty" json:"RItemList,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`

	DataBufferOverflow bool `xml:"DataBufferOverflow,attr,omitempty" json:"DataBufferOverflow,omitempty"`
}

type SubscriptionCancel struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ SubscriptionCancel"`

	ServerSubHandle string `xml:"ServerSubHandle,attr,omitempty" json:"ServerSubHandle,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`
}

type SubscriptionCancelResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ SubscriptionCancelResponse"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`
}

type Browse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ Browse"`

	PropertyNames []*QName `xml:"PropertyNames,omitempty" json:"PropertyNames,omitempty"`

	LocaleID string `xml:"LocaleID,attr,omitempty" json:"LocaleID,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ContinuationPoint string `xml:"ContinuationPoint,attr,omitempty" json:"ContinuationPoint,omitempty"`

	MaxElementsReturned int32 `xml:"MaxElementsReturned,attr,omitempty" json:"MaxElementsReturned,omitempty"`

	BrowseFilter *BrowseFilter `xml:"BrowseFilter,attr,omitempty" json:"BrowseFilter,omitempty"`

	ElementNameFilter string `xml:"ElementNameFilter,attr,omitempty" json:"ElementNameFilter,omitempty"`

	VendorFilter string `xml:"VendorFilter,attr,omitempty" json:"VendorFilter,omitempty"`

	ReturnAllProperties bool `xml:"ReturnAllProperties,attr,omitempty" json:"ReturnAllProperties,omitempty"`

	ReturnPropertyValues bool `xml:"ReturnPropertyValues,attr,omitempty" json:"ReturnPropertyValues,omitempty"`

	ReturnErrorText bool `xml:"ReturnErrorText,attr,omitempty" json:"ReturnErrorText,omitempty"`
}

type BrowseResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ BrowseResponse"`

	BrowseResult *ReplyBase `xml:"BrowseResult,omitempty" json:"BrowseResult,omitempty"`

	Elements []*BrowseElement `xml:"Elements,omitempty" json:"Elements,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`

	ContinuationPoint string `xml:"ContinuationPoint,attr,omitempty" json:"ContinuationPoint,omitempty"`

	MoreElements bool `xml:"MoreElements,attr,omitempty" json:"MoreElements,omitempty"`
}

type Read struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ Read"`

	Options *RequestOptions `xml:"Options,omitempty" json:"Options,omitempty"`

	ItemList *ReadRequestItemList `xml:"ItemList,omitempty" json:"ItemList,omitempty"`
}

type ReadResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ ReadResponse"`

	ReadResult *ReplyBase `xml:"ReadResult,omitempty" json:"ReadResult,omitempty"`

	RItemList *ReplyItemList `xml:"RItemList,omitempty" json:"RItemList,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`
}

type Write struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ Write"`

	Options *RequestOptions `xml:"Options,omitempty" json:"Options,omitempty"`

	ItemList *WriteRequestItemList `xml:"ItemList,omitempty" json:"ItemList,omitempty"`

	ReturnValuesOnReply bool `xml:"ReturnValuesOnReply,attr,omitempty" json:"ReturnValuesOnReply,omitempty"`
}

type WriteResponse struct {
	XMLName xml.Name `xml:"http://opcfoundation.org/webservices/XMLDA/1.0/ WriteResponse"`

	WriteResult *ReplyBase `xml:"WriteResult,omitempty" json:"WriteResult,omitempty"`

	RItemList *ReplyItemList `xml:"RItemList,omitempty" json:"RItemList,omitempty"`

	Errors []*OPCError `xml:"Errors,omitempty" json:"Errors,omitempty"`
}

type ReplyBase struct {
	RcvTime XSDDateTime `xml:"RcvTime,attr,omitempty" json:"RcvTime,omitempty"`

	ReplyTime XSDDateTime `xml:"ReplyTime,attr,omitempty" json:"ReplyTime,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`

	RevisedLocaleID string `xml:"RevisedLocaleID,attr,omitempty" json:"RevisedLocaleID,omitempty"`

	ServerState *ServerState `xml:"ServerState,attr,omitempty" json:"ServerState,omitempty"`
}

type ServerStatus struct {
	StatusInfo string `xml:"StatusInfo,omitempty" json:"StatusInfo,omitempty"`

	VendorInfo string `xml:"VendorInfo,omitempty" json:"VendorInfo,omitempty"`

	SupportedLocaleIDs []string `xml:"SupportedLocaleIDs,omitempty" json:"SupportedLocaleIDs,omitempty"`

	SupportedInterfaceVersions []*InterfaceVersion `xml:"SupportedInterfaceVersions,omitempty" json:"SupportedInterfaceVersions,omitempty"`

	StartTime XSDDateTime `xml:"StartTime,attr,omitempty" json:"StartTime,omitempty"`

	ProductVersion string `xml:"ProductVersion,attr,omitempty" json:"ProductVersion,omitempty"`
}

type ItemIdentifier struct {
	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`
}

type PropertyReplyList struct {
	Properties []*ItemProperty `xml:"Properties,omitempty" json:"Properties,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ResultID *QName `xml:"ResultID,attr,omitempty" json:"ResultID,omitempty"`
}

type ItemProperty struct {
	Value struct {
	} `xml:"Value,omitempty" json:"Value,omitempty"`

	Name *QName `xml:"Name,attr,omitempty" json:"Name,omitempty"`

	Description string `xml:"Description,attr,omitempty" json:"Description,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ResultID *QName `xml:"ResultID,attr,omitempty" json:"ResultID,omitempty"`
}

type OPCError struct {
	Text string `xml:"Text,omitempty" json:"Text,omitempty"`

	ID *QName `xml:"ID,attr,omitempty" json:"ID,omitempty"`
}

type ArrayOfUnsignedInt struct {
	UnsignedInt []uint32 `xml:"unsignedInt,omitempty" json:"unsignedInt,omitempty"`
}

type ArrayOfLong struct {
	Long []int64 `xml:"long,omitempty" json:"long,omitempty"`
}

type ArrayOfUnsignedLong struct {
	UnsignedLong []uint64 `xml:"unsignedLong,omitempty" json:"unsignedLong,omitempty"`
}

type ArrayOfInt struct {
	int []int32 `xml:"int,omitempty" json:"int,omitempty"`
}

type ArrayOfByte struct {
	byte []int8 `xml:"byte,omitempty" json:"byte,omitempty"`
}

type ArrayOfShort struct {
	Short []int16 `xml:"short,omitempty" json:"short,omitempty"`
}

type ArrayOfUnsignedShort struct {
	UnsignedShort []uint16 `xml:"unsignedShort,omitempty" json:"unsignedShort,omitempty"`
}

type ArrayOfFloat struct {
	Float []float32 `xml:"float,omitempty" json:"float,omitempty"`
}

type ArrayOfDecimal struct {
	Decimal []float64 `xml:"decimal,omitempty" json:"decimal,omitempty"`
}

type ArrayOfDouble struct {
	Double []float64 `xml:"double,omitempty" json:"double,omitempty"`
}

type ArrayOfBoolean struct {
	Boolean []bool `xml:"boolean,omitempty" json:"boolean,omitempty"`
}

type ArrayOfString struct {
	Astring []*string `xml:"string,omitempty" json:"string,omitempty"`
}

type ArrayOfDateTime struct {
	DateTime []XSDDateTime `xml:"dateTime,omitempty" json:"dateTime,omitempty"`
}

type ArrayOfAnyType struct {
	AnyType []struct {
	} `xml:"anyType,omitempty" json:"anyType,omitempty"`
}

type RequestOptions struct {
	ReturnErrorText bool `xml:"ReturnErrorText,attr,omitempty" json:"ReturnErrorText,omitempty"`

	ReturnDiagnosticInfo bool `xml:"ReturnDiagnosticInfo,attr,omitempty" json:"ReturnDiagnosticInfo,omitempty"`

	ReturnItemTime bool `xml:"ReturnItemTime,attr,omitempty" json:"ReturnItemTime,omitempty"`

	ReturnItemPath bool `xml:"ReturnItemPath,attr,omitempty" json:"ReturnItemPath,omitempty"`

	ReturnItemName bool `xml:"ReturnItemName,attr,omitempty" json:"ReturnItemName,omitempty"`

	RequestDeadline XSDDateTime `xml:"RequestDeadline,attr,omitempty" json:"RequestDeadline,omitempty"`

	ClientRequestHandle string `xml:"ClientRequestHandle,attr,omitempty" json:"ClientRequestHandle,omitempty"`

	LocaleID string `xml:"LocaleID,attr,omitempty" json:"LocaleID,omitempty"`
}

type SubscribeRequestItemList struct {
	Items []*SubscribeRequestItem `xml:"Items,omitempty" json:"Items,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ReqType *QName `xml:"ReqType,attr,omitempty" json:"ReqType,omitempty"`

	Deadband float32 `xml:"Deadband,attr,omitempty" json:"Deadband,omitempty"`

	RequestedSamplingRate int32 `xml:"RequestedSamplingRate,attr,omitempty" json:"RequestedSamplingRate,omitempty"`

	EnableBuffering bool `xml:"EnableBuffering,attr,omitempty" json:"EnableBuffering,omitempty"`
}

type SubscribeRequestItem struct {
	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ReqType *QName `xml:"ReqType,attr,omitempty" json:"ReqType,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ClientItemHandle string `xml:"ClientItemHandle,attr,omitempty" json:"ClientItemHandle,omitempty"`

	Deadband float32 `xml:"Deadband,attr,omitempty" json:"Deadband,omitempty"`

	RequestedSamplingRate int32 `xml:"RequestedSamplingRate,attr,omitempty" json:"RequestedSamplingRate,omitempty"`

	EnableBuffering bool `xml:"EnableBuffering,attr,omitempty" json:"EnableBuffering,omitempty"`
}

type SubscribeReplyItemList struct {
	Items []*SubscribeItemValue `xml:"Items,omitempty" json:"Items,omitempty"`

	RevisedSamplingRate int32 `xml:"RevisedSamplingRate,attr,omitempty" json:"RevisedSamplingRate,omitempty"`
}

type SubscribeItemValue struct {
	ItemValue *ItemValue `xml:"ItemValue,omitempty" json:"ItemValue,omitempty"`

	RevisedSamplingRate int32 `xml:"RevisedSamplingRate,attr,omitempty" json:"RevisedSamplingRate,omitempty"`
}

type ItemValue struct {
	DiagnosticInfo string `xml:"DiagnosticInfo,omitempty" json:"DiagnosticInfo,omitempty"`

	Value struct {
	} `xml:"Value,omitempty" json:"Value,omitempty"`

	Quality *OPCQuality `xml:"Quality,omitempty" json:"Quality,omitempty"`

	ValueTypeQualifier *QName `xml:"ValueTypeQualifier,attr,omitempty" json:"ValueTypeQualifier,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ClientItemHandle string `xml:"ClientItemHandle,attr,omitempty" json:"ClientItemHandle,omitempty"`

	Timestamp XSDDateTime `xml:"Timestamp,attr,omitempty" json:"Timestamp,omitempty"`

	ResultID *QName `xml:"ResultID,attr,omitempty" json:"ResultID,omitempty"`
}

type OPCQuality struct {
	QualityField *QualityBits `xml:"QualityField,attr,omitempty" json:"QualityField,omitempty"`

	LimitField *LimitBits `xml:"LimitField,attr,omitempty" json:"LimitField,omitempty"`

	VendorField byte `xml:"VendorField,attr,omitempty" json:"VendorField,omitempty"`
}

type SubscribePolledRefreshReplyItemList struct {
	Items []*ItemValue `xml:"Items,omitempty" json:"Items,omitempty"`

	SubscriptionHandle string `xml:"SubscriptionHandle,attr,omitempty" json:"SubscriptionHandle,omitempty"`
}

type BrowseElement struct {
	Properties []*ItemProperty `xml:"Properties,omitempty" json:"Properties,omitempty"`

	Name string `xml:"Name,attr,omitempty" json:"Name,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	IsItem bool `xml:"IsItem,attr,omitempty" json:"IsItem,omitempty"`

	HasChildren bool `xml:"HasChildren,attr,omitempty" json:"HasChildren,omitempty"`
}

type ReadRequestItemList struct {
	Items []*ReadRequestItem `xml:"Items,omitempty" json:"Items,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ReqType *QName `xml:"ReqType,attr,omitempty" json:"ReqType,omitempty"`

	MaxAge int32 `xml:"MaxAge,attr,omitempty" json:"MaxAge,omitempty"`
}

type ReadRequestItem struct {
	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`

	ReqType *QName `xml:"ReqType,attr,omitempty" json:"ReqType,omitempty"`

	ItemName string `xml:"ItemName,attr,omitempty" json:"ItemName,omitempty"`

	ClientItemHandle string `xml:"ClientItemHandle,attr,omitempty" json:"ClientItemHandle,omitempty"`

	MaxAge int32 `xml:"MaxAge,attr,omitempty" json:"MaxAge,omitempty"`
}

type ReplyItemList struct {
	Items []*ItemValue `xml:"Items,omitempty" json:"Items,omitempty"`

	Reserved string `xml:"Reserved,attr,omitempty" json:"Reserved,omitempty"`
}

type WriteRequestItemList struct {
	Items []*ItemValue `xml:"Items,omitempty" json:"Items,omitempty"`

	ItemPath string `xml:"ItemPath,attr,omitempty" json:"ItemPath,omitempty"`
}

type OpcXmlDASoap interface {
	GetStatus(request *GetStatus) (*GetStatusResponse, error)

	GetStatusContext(ctx context.Context, request *GetStatus) (*GetStatusResponse, error)

	GetProperties(request *GetProperties) (*GetPropertiesResponse, error)

	GetPropertiesContext(ctx context.Context, request *GetProperties) (*GetPropertiesResponse, error)

	Subscribe(request *Subscribe) (*SubscribeResponse, error)

	SubscribeContext(ctx context.Context, request *Subscribe) (*SubscribeResponse, error)

	SubscriptionPolledRefresh(request *SubscriptionPolledRefresh) (*SubscriptionPolledRefreshResponse, error)

	SubscriptionPolledRefreshContext(ctx context.Context, request *SubscriptionPolledRefresh) (*SubscriptionPolledRefreshResponse, error)

	SubscriptionCancel(request *SubscriptionCancel) (*SubscriptionCancelResponse, error)

	SubscriptionCancelContext(ctx context.Context, request *SubscriptionCancel) (*SubscriptionCancelResponse, error)

	Browse(request *Browse) (*BrowseResponse, error)

	BrowseContext(ctx context.Context, request *Browse) (*BrowseResponse, error)

	Read(request *Read) (*ReadResponse, error)

	ReadContext(ctx context.Context, request *Read) (*ReadResponse, error)

	Write(request *Write) (*WriteResponse, error)

	WriteContext(ctx context.Context, request *Write) (*WriteResponse, error)
}

type opcXmlDASoap struct {
	client *soap.Client
}

func NewOpcXmlDASoap(client *soap.Client) OpcXmlDASoap {
	return &opcXmlDASoap{
		client: client,
	}
}

func (service *opcXmlDASoap) GetStatusContext(ctx context.Context, request *GetStatus) (*GetStatusResponse, error) {
	response := new(GetStatusResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/GetStatus", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) GetStatus(request *GetStatus) (*GetStatusResponse, error) {
	return service.GetStatusContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) GetPropertiesContext(ctx context.Context, request *GetProperties) (*GetPropertiesResponse, error) {
	response := new(GetPropertiesResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/GetProperties", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) GetProperties(request *GetProperties) (*GetPropertiesResponse, error) {
	return service.GetPropertiesContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) SubscribeContext(ctx context.Context, request *Subscribe) (*SubscribeResponse, error) {
	response := new(SubscribeResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/Subscribe", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) Subscribe(request *Subscribe) (*SubscribeResponse, error) {
	return service.SubscribeContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) SubscriptionPolledRefreshContext(ctx context.Context, request *SubscriptionPolledRefresh) (*SubscriptionPolledRefreshResponse, error) {
	response := new(SubscriptionPolledRefreshResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionPolledRefresh", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) SubscriptionPolledRefresh(request *SubscriptionPolledRefresh) (*SubscriptionPolledRefreshResponse, error) {
	return service.SubscriptionPolledRefreshContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) SubscriptionCancelContext(ctx context.Context, request *SubscriptionCancel) (*SubscriptionCancelResponse, error) {
	response := new(SubscriptionCancelResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionCancel", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) SubscriptionCancel(request *SubscriptionCancel) (*SubscriptionCancelResponse, error) {
	return service.SubscriptionCancelContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) BrowseContext(ctx context.Context, request *Browse) (*BrowseResponse, error) {
	response := new(BrowseResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/Browse", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) Browse(request *Browse) (*BrowseResponse, error) {
	return service.BrowseContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) ReadContext(ctx context.Context, request *Read) (*ReadResponse, error) {
	response := new(ReadResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/Read", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) Read(request *Read) (*ReadResponse, error) {
	return service.ReadContext(
		context.Background(),
		request,
	)
}

func (service *opcXmlDASoap) WriteContext(ctx context.Context, request *Write) (*WriteResponse, error) {
	response := new(WriteResponse)
	err := service.client.CallContext(ctx, "http://opcfoundation.org/webservices/XMLDA/1.0/Write", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *opcXmlDASoap) Write(request *Write) (*WriteResponse, error) {
	return service.WriteContext(
		context.Background(),
		request,
	)
}
